### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [dariusmp0/splurty#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by dariusmp0** [comment]
Added the "viewport" meta tag into the "head" tag in my application.html.erb. It is a lot easier to read on my phone. Thanks

**Comment by Mikeysax** [comment]
👍
